version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - run:
          name: install firebase
          command: |
            npm install -g firebase-tools
      - run:
          name: preparation
          command: |
            git clone https://bitbucket.org/wakabatan/suikaweb-pubdata.git local/pubdata --depth 1
            tar xf local/pubdata/hero-public.tar
            mkdir -p public && mv public_html public/hero
      - deploy:
          name: firebase
          command: |
            echo "{\"firebase\":\"$FIREBASE_NAME\", \"public\":\"public\", \"ignore\":[\"**/.*\"]}" > firebase.json
            firebase deploy:hosting --token $FIREBASE_TOKEN
